language: node_js
node_js: stable
branches:
  only:
    - master

# S: Build Lifecycle
install:
  - yarn

script:
  - yarn build-docs

after_success:
  - cd ./packages/docs/dist
  - echo ${GH_CNAME} > CNAME
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "${GH_USER_EMAIL}"
  - git add .
  - git commit -m "Build $(date +%Y%m%d%H%M)"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REPO}" master:gh-pages
# E: Build LifeCycle
