version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10

commands:
  install:
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save node_modules Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

jobs:
  lint:
    executor: node
    steps:
      - install
      - run:
          name: Lint Code
          command: yarn lint

  # build docs and publish to gh-pages
  build_docs_and_publish:
    executor: node
    steps:
      - install
      - run:
          name: Build Docs
          command: yarn build-docs
      - run:
          name: Publish Github Pages
          command: |
            cd ./packages/docs/dist
            echo ${GH_CNAME} > CNAME
            git init
            git config user.name "${GH_USER_NAME}"
            git config user.email "${GH_USER_EMAIL}"
            git add .
            git commit -m "Build $(date +%Y%m%d%H%M)"
            git push --force --quiet "https://${GH_TOKEN}@${GH_REPO}" master:gh-pages

workflows:
  version: 2
  github_pages:
    jobs:
      - build_docs_and_publish:
          filters:
            branches:
              only: master
  check:
    jobs:
      - lint:
          filters:
            branches:
              ignore: gh-pages
